### ISSUE TITLE
UhcCore Maven dependency

### ISSUE THREAD

**Issue by 0dinD** [Rexe0/UHCChampions#2]
Just a small tip for you: :slightly_smiling_face:

I noticed you are using a manually configured dependency on UhcCore as a local file: https://github.com/Rexe0/UHCChampions/blob/6233c6a98cb99ba2328b61fb27c5f040bbdbcada/pom.xml#L78

But you could add the dependency via the UhcCore Maven repository instead, as mentioned here (click on the "Maven" tab since you're using Maven): https://uhccore.zerodind.net/faq/#does-uhccore-have-an-addon-api

That way, it's easier to update UhcCore, you can just update the version number in the `pom.xml` instead of downloading the new version manually. And it also makes it easier for other people to build your source code. :slightly_smiling_face:

**Comment by Rexe0** [comment]
Oh, I'm actually not sure how it ended up like that but thanks for pointing it out. I will see if I can change it.

**Comment by Rexe0** [comment]
Alright, that should have fixed it. Let me know if you have any other tips or concerns. Thanks.

**Comment by 0dinD** [comment]
Cool! Yeah I just saw it and thought I'd let you know in case you didn't know about the UhcCore Maven repostitory. :slightly_smiling_face:
